### ISSUE TITLE
Set up  Cypress

### ISSUE THREAD

**Issue by angelocordon** [We-Are-The-Crew/jobrace#1]
Set up Cypress for testing. 
https://www.cypress.io/

**Comment by josephrexme** [comment]
We can create a `ui-tests` folder at the root directory and use `data-tst` on elements we want to select during the E2E testing

**Comment by josephrexme** [comment]
We can also try to hook this up with Github Actions

**Comment by angelocordon** [comment]
What is `data-tst`? you mean just a data attribute?

**Comment by josephrexme** [comment]
Yes. When writing the page selectors for the cypress tests we want to use the test data attribute on elements to select them rather than relying on some classes or ids. So we could have:

```html
<button data-tst="signup-btn">Sign Up</button>
```

And for every React component we create we will have a `test` prop whose value is passed down to the element and then passed into `data-tst`
